### PR TITLE
#485 Regenerate golden images

### LINKED ISSUE #485: Regenerate golden images
It seems that rendering settings in chromedriver (?) have changed - golden images mismatch in a noisy pattern around sprite edges. We need to update the golden images to be able to catch errors while working on tasks related to rendering (like updating threejs).

### PR DESCRIPTION
**Pull request by paulsmirnov**
## Description

Closes #485. I updated the settings to remove axes from the images before regenerating them. Also, the comparison threshold is now non-zero to account for minor changes in screenshots due to chromedriver version. At least that's how we see it currently.

Note: fbx exporter tests are broken but they are out of scope of this task.

## Type of changes

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read [CONTRIBUTING](https://github.com/epam/miew/blob/master/CONTRIBUTING.md) and [CODE_OF_CONDUCT](https://github.com/epam/miew/blob/master/CODE_OF_CONDUCT.md) guides.
- [x] I have followed the code style of this project.
- [x] I have run `yarn run ci`: lint and tests pass locally with my changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] The changes do not need docs update.

### CODE REVIEW

**Comment by paulsmirnov** [comment]
To verify:

```
yarn && yarn run ci
yarn packages/lib run test:e2e
```

**Review by NataliaDSmirnova — APPROVED** [review]
All e2e tests pass except fbx exporting, but as I know that' expected.
Thank you!

**Comment by DmitryLukyanov** [comment]
Second attempt was successful in my case. LGTM)

**Review by DmitryLukyanov — DISMISSED** [review]

**Comment by paulsmirnov** [comment]
On another computer, I had 0.07% differences with the threshold of 0.05%. We can raise the threshold or try to understand the reason. Or both :)

**Review by NataliaDSmirnova — APPROVED** [review]

**Pull request merged**
